apiVersion: hyperspike.io/v1
kind: Gitea
metadata:
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: git
spec:
  tls: true
  #objectStorage:
  #  type: s3
  certIssuer: selfsigned
  prometheus: true
  prometheusLabels:
    prometheus: prometheus
  valkey: true
  ingress:
    #annotations:
    #  cert-manager.io/cluster-issuer: letsencrypt
    host: git.local.net
---
apiVersion: hyperspike.io/v1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: demo
spec:
  email: demo@git.local
  password:
    name: demo-password
    key: password
  instance:
    name: git
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-password
type: Opaque
stringData:
  password: test1234
---
apiVersion: hyperspike.io/v1
kind: Org
metadata:
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: test
spec:
  description: Test Env for Operator
  instance:
    name: git
  teams:
  - name: Test
    permission: admin
    includeAllRepos: true
    members:
    - demo
#---
#apiVersion: hyperspike.io/v1
#kind: Repo
#metadata:
#  labels:
#    app.kubernetes.io/name: gitea-operator
#    app.kubernetes.io/managed-by: kustomize
#  name: repo-sample
#spec:
#  private: true
#  org:
#    name: test
#---
#apiVersion: hyperspike.io/v1
#kind: Repo
#metadata:
#  labels:
#    app.kubernetes.io/name: gitea-operator
#    app.kubernetes.io/managed-by: kustomize
#  name: two
#spec:
#  private: true
#  org:
#    name: test
