# permissions for end users to edit orgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: org-editor-role
rules:
- apiGroups:
  - hyperspike.io
  resources:
  - orgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hyperspike.io
  resources:
  - orgs/status
  verbs:
  - get
