apiVersion: hyperspike.io/v1
kind: Repo
metadata:
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: repo-sample
spec:
  private: true
  org:
    name: test
  # TODO(user): Add fields here
