apiVersion: hyperspike.io/v1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: test
spec:
  email: test@git.local
  password:
    name: test-password
    key: password
  instance:
    name: gitea
---
apiVersion: v1
kind: Secret
metadata:
  name: test-password
type: Opaque
stringData:
  password: test1234
