apiVersion: hyperspike.io/v1
kind: Runner
metadata:
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: runner-sample
spec:
  # TODO(user): Add fields here
